backend:
  name: github
  repo: mervin589/Blvck-Accessories-
  branch: main
  auth_endpoint: https://api.staticcms.org/v1/auth

media_library:
  name: cloudinary
  config:
    cloud_name: ddpxau7gi
    api_key: 778782596942275
    
collections:
    - name: "products"
    label: "Products"
    folder: "_products"
    create: true
    fields:
            - {label: "Name", name: "name", widget: "string"}
            - {label: "Price", name: "price", widget: "string"}
            - {label: "Category", name: "category", widget: "select", options: ["Bags", "Necklaces", "Hats"]}
            - {label: "Image", name: "image", widget: "image"}
