backend:
  name: github
  repo: mervin589/Blvck-Accessories-
  branch: main
  auth_endpoint: https://api.staticcms.org/v1/auth

# This section enables the upload button
media_folder: "assets/products"
public_folder: "/assets/products"

collections:
  - name: "products"
    label: "Products"
    folder: "_products"
    create: true
    slug: "{{name}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["AirPods", "Watches", "Bags", "Sunglasses"]}
      - {label: "Product Image", name: "image", widget: "image", choose_url: false}
      - {label: "Description", name: "body", widget: "markdown"}
